name: Tag on Push

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed  # Ensures it only triggers when a PR is merged

jobs:
  create-tag:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Generate Tag Name
        id: generate_tag
        run: |
          # Example: Create a tag based on date
          TAG_NAME="v$(date -u +'%Y.%m.%d').${GITHUB_RUN_NUMBER}"
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV

      - name: Create and Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ env.tag_name }}
          git push origin ${{ env.tag_name }}
